version: 2

jobs:
  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: tgremlin82/terraform_ansible_aws:1.0
    steps:
      - checkout
      - run:
        name: terraform init & plan
        command: |
          terraform init -input=false
          terraform plan -out tfapply
          